# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67fea0100e3444479f2f61289d190b451f07db800ce062ff282b60b95ad6f4c45851d698a78da5a611f6e554f3ef8d22bea1a1bdb750dbd25f017be88534635e

test:
  secret_key_base: 0c925dccad1bd5b76bee3bd159b915bfff4bef94c9d87aee9e25a09459ef62a3b6a29b1493e8a0f411fdb2bb3643a2f3916d8ecfd3a7e0d6921cdef7657f6719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
